<?xml version="1.0" encoding="UTF-8"?>
<project xmlns="http://maven.apache.org/POM/4.0.0"
         xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
         xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/xsd/maven-4.0.0.xsd">
    <modelVersion>4.0.0</modelVersion>

    <groupId>ecology9.second</groupId>
    <artifactId>_demo</artifactId>
    <version>26.09.01</version>

    <properties>
        <!-- E9 二开必须使用 JDK 1.8，严格指定编译与源码级别 -->
        <maven.compiler.source>1.8</maven.compiler.source>
        <maven.compiler.target>1.8</maven.compiler.target>
        <project.build.sourceEncoding>UTF-8</project.build.sourceEncoding>
        <project.reporting.outputEncoding>UTF-8</project.reporting.outputEncoding>
    </properties>

    <distributionManagement>
        <repository>
            <id>nexus-solelyr-public</id>
            <url>https://nexus.solelyz.cn/repository/maven-public/</url>
        </repository>
    </distributionManagement>

    <dependencies>
        <dependency>
            <groupId>ecology9.second</groupId>
            <artifactId>weaver</artifactId>
            <version>9.00.2601.01</version>
        </dependency>
        <dependency>
            <groupId>ecology9.second</groupId>
            <artifactId>_solelyr</artifactId>
            <version>26.09.0.1</version>
        </dependency>
    </dependencies>

    <build>
        <plugins>
            <plugin>
                <groupId>org.apache.maven.plugins</groupId>
                <artifactId>maven-compiler-plugin</artifactId>
                <version>3.8.1</version>
                <configuration>
                    <source>1.8</source>
                    <target>1.8</target>
                    <encoding>UTF-8</encoding>
                    <!-- 通过软链的方式 将本地weaver lib 目录下的所有 jar 加入 JDK 8 的扩展类路径。 -->
                    <compilerArgs>
                        <arg>-extdirs</arg>
                        <arg>${project.basedir}/ecology/WEB-INF/lib</arg>
                    </compilerArgs>
                </configuration>
            </plugin>
        </plugins>
    </build>

</project>
