db0.DriverClasses=com.xugu.cloudjdbc.Driver
db0.showname=xugu
db0.origintype=xg
db0.dbtype=oracle
db0.url=jdbc:xugu://{host}:{port}/{database}?keyword_filter=TIME,DATETIME,SEPARATOR,POLICY,MEMBER,FORALL,LINK,CONSTANT,LIMIT,EXPLAIN,TOP,LOCAL&CompatibleOracle=true


db1.DriverClasses=sundb.jdbc.driver.sundbDriver
db1.showname=sundb
db1.origintype=kl
db1.dbtype=oracle
db1.url=jdbc:sundb://{host}:{port}/{database}

db2.DriverClasses=com.dbcp.jdbc.Driver
db2.showname=tydb
db2.origintype=ty
db2.dbtype=oracle
db2.url=jdbc:dbcp://{host}:{port}/{database}?convert_mode=1

db3.DriverClasses=cn.com.vastbase.Driver
db3.showname=vastbase_oracle
db3.origintype=vbora
db3.dbtype=oracle
db3.url=jdbc:vastbase://{host}:{port}/{database}?connectTimeout=0&socketTimeout=0&preferQueryMode=simple

db4.DriverClasses=com.yashandb.jdbc.Driver
db4.showname=yasdb
db4.origintype=yas
db4.dbtype=oracle
db4.url=jdbc:yasdb://{host}:{port}/{database}?allowSemicolonTerminator=true

